#error display
server:
  error:
    whitelabel:
      enabled: false
  context-path: /

spring:
  thymeleaf:
    cache: false
  #Date Format
  mvc:
    date-format: yyyy/MM/dd

  #JDBC (設定がひとつ必要なので用意しておく、必要に応じて違うデータベース用に書き換えること）
  datasource:
    url: jdbc:sqlserver://172.0.0.1;databaseName=DatabaseName
    username: hoge
    password: fuga
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #max-wait: 5000
    #max-active: 200
    #max-idle: 50
    #initial-size: 5
    #test-while-idle: true
    #test-on-borrow: true
    #test-on-connect: true
    #validation-query: SELECT GETDATE()

  #以下、バリデーションにて使用する設定。
  #メッセージファイルの所在、src/main/resourcesを基準に設定する。
  messages:
    basename: messages, validateMessages
    cache-seconds: -1
    encoding: UTF-8

security:
  basic:
    # Basic認証を使用する場合は True
    enabled: false
    
#Mybatis
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    use-column-label: true

#Log output settings
logging:
  path: log
#  level:
#    jp.co.ixui.spring.boilerplate.mapper: DEBUG


